In [1]:
import pandas as pd

# Load Excel files
file1 = pd.read_excel("D:\BIOINFORMATICS\OMICS LOGIC\PROJECTS\combined_data\GSE123658-GPL18573_series_matrix.xlsx")
file2 = pd.read_excel("D:\BIOINFORMATICS\OMICS LOGIC\PROJECTS\combined_data\GSE123658-GPL20301_series_matrix.xlsx")

In [3]:
import pandas as pd

# File paths (your uploaded files)
file1_path = "D:\BIOINFORMATICS\OMICS LOGIC\PROJECTS\combined_data\GSE123658-GPL18573_series_matrix.xlsx"
file2_path = "D:\BIOINFORMATICS\OMICS LOGIC\PROJECTS\combined_data\GSE123658-GPL20301_series_matrix.xlsx"

# Load both Excel files
df1 = pd.read_excel(file1_path, header=None)
df2 = pd.read_excel(file2_path, header=None)

In [4]:
df1.head()

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,!Series_title,Transimmunom whole blood RNA-seq data from ty...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,!Series_geo_accession,GSE123658,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,!Series_status,Public on Jun 01 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,!Series_submission_date,Dec 11 2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,!Series_last_update_date,Jun 03 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Rows to extract
rows_needed = ["!Sample_title", "!Sample_characteristics_ch1"]

# Extract required rows from file1
extract1 = df1[df1[0].isin(rows_needed)]

# Extract required rows from file2
extract2 = df2[df2[0].isin(rows_needed)]

In [6]:
# Combine both side-by-side
combined = pd.concat([extract1, extract2], axis=1)

In [7]:
combined.head()

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
34,!Sample_title,healthy subject ID:1790,healthy subject ID:471e,healthy subject ID:4d4e,healthy subject ID:50e8,healthy subject ID:7f1a,healthy subject ID:8cd0,healthy subject ID:98a3,healthy subject ID:ad10,healthy subject ID:bb58,...,healthy subject ID:eba3,healthy subject ID:fb03,healthy subject ID:fbbe,healthy subject ID:fbfa,T1D subject ID:082a,T1D subject ID:1d36,T1D subject ID:3f22,T1D subject ID:5cd9,T1D subject ID:b857,T1D subject ID:cf1e
43,!Sample_characteristics_ch1,patient diagnosis: healthy,patient diagnosis: healthy,patient diagnosis: healthy,patient diagnosis: healthy,patient diagnosis: healthy,patient diagnosis: healthy,patient diagnosis: healthy,patient diagnosis: healthy,patient diagnosis: healthy,...,patient diagnosis: healthy,patient diagnosis: healthy,patient diagnosis: healthy,patient diagnosis: healthy,patient diagnosis: type 1 diabetes,patient diagnosis: type 1 diabetes,patient diagnosis: type 1 diabetes,patient diagnosis: type 1 diabetes,patient diagnosis: type 1 diabetes,patient diagnosis: type 1 diabetes
44,!Sample_characteristics_ch1,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,...,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood,tissue: Whole blood
45,!Sample_characteristics_ch1,Sex: F,Sex: F,Sex: M,Sex: F,Sex: F,Sex: F,Sex: F,Sex: M,Sex: M,...,Sex: F,Sex: F,Sex: M,Sex: M,Sex: M,Sex: M,Sex: M,Sex: M,Sex: M,Sex: F
46,!Sample_characteristics_ch1,age: 28,age: 41,age: 24,age: 44,age: 35,age: 45,age: 56,age: 32,age: 46,...,age: 35,age: 45,age: 47,age: 30,age: 36,age: 33,age: 26,age: 37,age: 29,age: 30

In [8]:
# Save into new Excel file
output_path = "D:/BIOINFORMATICS/OMICS LOGIC/PROJECTS/combined_data/combined_sample_info.xlsx"
combined.to_excel(output_path, index=False, header=False)

print("Combined Excel file created successfully!")
print("Saved at:", output_path)

Combined Excel file created successfully!
Saved at: D:/BIOINFORMATICS/OMICS LOGIC/PROJECTS/combined_data/combined_sample_info.xlsx

In [10]:
combined.shape

(6, 84)

In [ ]:
combined -- spliting

In [12]:
# Find the row where first column is "!Sample_title"
sample_idx = combined[combined.iloc[:, 0] == "!Sample_title"].index

# Extract that row
sample_row = combined.loc[sample_idx[0]]

# Create list to store separated rows
rows = []

# Loop through all values in that row (excluding first column)
for val in sample_row[1:]:
    if isinstance(val, str) and "ID:" in val:
        # Split into subject type and ID
        part1, part2 = val.split("ID:")

        rows.append({
            "Subject_Type": part1.strip() + "ID",
            "ID_Value": part2.strip()
        })
    else:
        rows.append({
            "Subject_Type": val,
            "ID_Value": ""
        })

# Convert into DataFrame
output_df = pd.DataFrame(rows)

In [13]:
output_df.head()

        Subject_Type ID_Value
0  healthy subjectID     1790
1  healthy subjectID     471e
2  healthy subjectID     4d4e
3  healthy subjectID     50e8
4  healthy subjectID     7f1a

In [14]:
output_df.shape

(83, 2)

In [15]:
# Save into new Excel file
out_path = "D:/BIOINFORMATICS/OMICS LOGIC/PROJECTS/combined_data/combined_data.xlsx"
output_df.to_excel(out_path, index=False)

print("File saved successfully:", out_path)

File saved successfully: D:/BIOINFORMATICS/OMICS LOGIC/PROJECTS/combined_data/combined_data.xlsx

In [ ]:
##### matches with subject type

In [16]:
read_counts = pd.read_excel("D:\BIOINFORMATICS\OMICS LOGIC\PROJECTS\combined_data\GSE123658_read_counts.gene_level.xlsx")

In [17]:
read_counts.head()

,Samples,131,341,04b3,865,08d3,990,107f,1790,20fe,...,bc66,c173,cf1e,d119,d76a,db19,db6e,dc2c,e2da,eb23
0,ENSG00000237683,3267,10391,1822,5399,15902,1355,4379,1274,2820,...,892,3165,1375,1033,732,2889,721,1290,1364,1069
1,ENSG00000269831,1,5,3,1,1,2,3,0,1,...,0,0,0,1,1,0,1,2,1,0
2,ENSG00000187634,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ENSG00000188976,1397,3683,969,2215,6043,887,1321,508,2702,...,564,919,648,1122,350,780,785,1068,691,614
4,ENSG00000187961,250,869,226,490,1330,151,115,78,390,...,205,237,71,351,56,376,138,282,181,135

In [18]:
# Step 2: Extract sample column names from read_counts
# -------------------------------
sample_columns = read_counts.columns.tolist()

# First column is gene name
gene_col = sample_columns[0]

# Remaining columns are sample IDs
sample_ids = sample_columns[1:]

# -------------------------------
# Step 3: Create mapping: ID_Value → Subject_Type
# -------------------------------
id_to_subject = dict(
    zip(output_df["ID_Value"].astype(str),
        output_df["Subject_Type"].astype(str))
)

# -------------------------------
# Step 4: Keep only matched sample IDs
# -------------------------------
matched_samples = [s for s in sample_ids if s in id_to_subject]

print("Matched Samples:", len(matched_samples))

# Filter read_counts
filtered_read_counts = read_counts[[gene_col] + matched_samples]

# -------------------------------
# Step 5: Replace sample IDs with Subject_Type in column headers
# -------------------------------
new_column_names = [gene_col]

for sample in matched_samples:
    subject_type = id_to_subject[sample]
    new_column_names.append(subject_type)

# Apply new column names
filtered_read_counts.columns = new_column_names

Matched Samples: 71

In [19]:
read_counts.head()

,Samples,131,341,04b3,865,08d3,990,107f,1790,20fe,...,bc66,c173,cf1e,d119,d76a,db19,db6e,dc2c,e2da,eb23
0,ENSG00000237683,3267,10391,1822,5399,15902,1355,4379,1274,2820,...,892,3165,1375,1033,732,2889,721,1290,1364,1069
1,ENSG00000269831,1,5,3,1,1,2,3,0,1,...,0,0,0,1,1,0,1,2,1,0
2,ENSG00000187634,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ENSG00000188976,1397,3683,969,2215,6043,887,1321,508,2702,...,564,919,648,1122,350,780,785,1068,691,614
4,ENSG00000187961,250,869,226,490,1330,151,115,78,390,...,205,237,71,351,56,376,138,282,181,135

In [20]:
read_counts.columns

Index([ 'Samples',        131,        341,     '04b3',        865,     '08d3',
              990,     '107f',       1790,     '20fe',     '2ac7',     '32d0',
           '3a5c',     '45d4',     '471e',     '4d4e', 5000000000,     '5dbf',
           '737b',     '74b4',     '74ca',     '7f1a',     '8cd0',     '98a3',
           'ac48',     'ad10',     'b3ea',     'b462',     'bb58',     'c44c',
           'c8a9',     'cc82',     'd23c',     'e2c4',     'e42f',     'e5ac',
           'e6b4',     'eba3',     'f27d',     'fb03',     'fbbe',     'fbf7',
           'fbfa',     'fe48',         89,     '04b0',     '082a',        935,
           '09cf',     '0d40',       1250,     '14df',     '1a72',     '1d36',
           '2b2b',     '38b0',     '3f22',     '54c3',     '5cd9',     '5ed7',
           '64a0',       6733,     '71b1',     '726e',     '7d99',       8185,
           '82a5',     '903a',     '9c1a',     'a15a',     'b302',     'b73e',
           'b857',     'bc66',     'c173',     'cf1e',     'd119',     'd76a',
           'db19',     'db6e',     'dc2c',     'e2da',     'eb23'],
      dtype='object')

In [26]:
output_df['ID_Value'].unique()

array(['1790', '471e', '4d4e', '50e8', '7f1a', '8cd0', '98a3', 'ad10',
       'bb58', 'c8a9', 'e5ac', 'f27d', 'fbf7', 'fe48', '0089', '04b0',
       '0935', '09cf', '0d40', '1250', '14df', '1a72', '2b2b', '38b0',
       '54c3', '5ed7', '64a0', '6733', '71b1', '726e', '7d99', '8185',
       '82a5', '903a', '9c1a', 'a15a', 'b302', 'b73e', 'bc66', 'c173',
       'd119', 'd76a', 'db19', 'db6e', 'dc2c', 'e2da', 'eb23', '', '0131',
       '0341', '04b3', '0865', '08d3', '0990', '107f', '20fe', '2ac7',
       '32d0', '3a5c', '45d4', '5dbf', '737b', '74b4', '74ca', 'ac48',
       'b3ea', 'b462', 'c44c', 'cc82', 'd23c', 'e2c4', 'e42f', 'e6b4',
       'eba3', 'fb03', 'fbbe', 'fbfa', '082a', '1d36', '3f22', '5cd9',
       'b857', 'cf1e'], dtype=object)

match the sample ids and get the group info -- by converting to the csv file both with matches with same sample ids

In [29]:
combined_data1 = pd.read_csv("D:\BIOINFORMATICS\OMICS LOGIC\PROJECTS\combined_data\Metadata-GSE123658.csv")

In [30]:
combined_data1.head()

  Sample_ID Group_info
0      1790    healthy
1      471e    healthy
2      4d4e    healthy
3  5.00E+09    healthy
4      7f1a    healthy

In [33]:
combined_data1['Sample_ID'].unique()

array(['1790', '471e', '4d4e', '5.00E+09', '7f1a', '8cd0', '98a3', 'ad10',
       'bb58', 'c8a9', 'e5ac', 'f27d', 'fbf7', 'fe48', '89', '04b0',
       '935', '09cf', '0d40', '1250', '14df', '1a72', '2b2b', '38b0',
       '54c3', '5ed7', '64a0', '6733', '71b1', '726e', '7d99', '8185',
       '82a5', '903a', '9c1a', 'a15a', 'b302', 'b73e', 'bc66', 'c173',
       'd119', 'd76a', 'db19', 'db6e', 'dc2c', 'e2da', 'eb23', '131',
       '341', '04b3', '865', '08d3', '990', '107f', '20fe', '2ac7',
       '32d0', '3a5c', '45d4', '5dbf', '737b', '74b4', '74ca', 'ac48',
       'b3ea', 'b462', 'c44c', 'cc82', 'd23c', 'e2c4', 'e42f', 'e6b4',
       'eba3', 'fb03', 'fbbe', 'fbfa', '082a', '1d36', '3f22', '5cd9',
       'b857', 'cf1e'], dtype=object)

In [34]:
read_count1 = pd.read_csv("D:\BIOINFORMATICS\OMICS LOGIC\PROJECTS\combined_data\GSE123658_read_counts.gene_level_2.csv")

In [35]:
read_count1.columns

Index(['Samples', '131', '341', '04b3', '865', '08d3', '990', '107f', '1790',
       '20fe', '2ac7', '32d0', '3a5c', '45d4', '471e', '4d4e', '5.00E+09',
       '5dbf', '737b', '74b4', '74ca', '7f1a', '8cd0', '98a3', 'ac48', 'ad10',
       'b3ea', 'b462', 'bb58', 'c44c', 'c8a9', 'cc82', 'd23c', 'e2c4', 'e42f',
       'e5ac', 'e6b4', 'eba3', 'f27d', 'fb03', 'fbbe', 'fbf7', 'fbfa', 'fe48',
       '89', '04b0', '082a', '935', '09cf', '0d40', '1250', '14df', '1a72',
       '1d36', '2b2b', '38b0', '3f22', '54c3', '5cd9', '5ed7', '64a0', '6733',
       '71b1', '726e', '7d99', '8185', '82a5', '903a', '9c1a', 'a15a', 'b302',
       'b73e', 'b857', 'bc66', 'c173', 'cf1e', 'd119', 'd76a', 'db19', 'db6e',
       'dc2c', 'e2da', 'eb23'],
      dtype='object')

In [36]:
#Step 2: Extract sample names from read_count1 columns
# -------------------------------

sample_names = read_count1.columns.tolist()

# -------------------------------
# Step 3: Create mapping: Sample_ID → Group_info
# -------------------------------

sample_to_group = dict(
    zip(combined_data1["Sample_ID"], combined_data1["Group_info"])
)

# -------------------------------
# Step 4: Replace sample names with Group_info
# -------------------------------

new_columns = []

for sample in sample_names:
    if sample in sample_to_group:
        new_columns.append(sample_to_group[sample])
    else:
        new_columns.append(sample)  # keep unchanged if no match

read_count1.columns = new_columns

In [37]:
read_count1.head()

,Samples,healthy,healthy,healthy,healthy,healthy,healthy,healthy,healthy,healthy,...,T1D,T1D,T1D,T1D,T1D,T1D,T1D,T1D,T1D,T1D
0,ENSG00000237683,3267,10391,1822,5399,15902,1355,4379,1274,2820,...,892,3165,1375,1033,732,2889,721,1290,1364,1069
1,ENSG00000269831,1,5,3,1,1,2,3,0,1,...,0,0,0,1,1,0,1,2,1,0
2,ENSG00000187634,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ENSG00000188976,1397,3683,969,2215,6043,887,1321,508,2702,...,564,919,648,1122,350,780,785,1068,691,614
4,ENSG00000187961,250,869,226,490,1330,151,115,78,390,...,205,237,71,351,56,376,138,282,181,135

In [38]:
read_count1.shape

(16785, 83)

In [39]:
# Step 5: Save updated file
# -------------------------------

read_count1.to_csv("read_count1_updated.csv")

print("✅ Samples matched and replaced with Group_info successfully!")

✅ Samples matched and replaced with Group_info successfully!